name: Test
on:
  pull_request:
  push:
    branches:
      - main
      - "release/*"
jobs:
  test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install move
        run: |
          cargo install mv-cli --features address20
      - name: Run Test
        run: |
          cargo test
